// _components/NavBar.tsx
import React from "react";

export default () => (
  <nav className="h-16 shadow-sm z-20 border-b border-gray-300">
    <div className="container mx-auto h-full flex flex-row items-center justify-between px-4">
      <div className="flex flex-row items-center">
        <a href="/" className="navlink">Wiwa</a>
      </div>
      <div className="flex flex-row items-center space-x-4">
        <a href="/blog" className="navlink">Blog</a>
        <a href="/projects" className="navlink">Projects</a>
      </div>
    </div>
  </nav>
);

// components/NavBar.vue
<template>
  <nav class="h-16 shadow-sm z-20 border-b border-gray-300">
    <div
      class="container mx-auto h-full flex flex-row items-center justify-between px-4"
    >
      <div class="flex flex-row items-center">
        <nuxt-link to="/" class="navlink">
          Wiwa
        </nuxt-link>
      </div>
      <div class="flex flex-row items-center space-x-4">
        <nuxt-link to="/blog" class="navlink">Blog</nuxt-link>
        <nuxt-link to="/projects" class="navlink">Projects</nuxt-link>
      </div>
    </div>
  </nav>
</template>

<script lang="ts">
import { defineComponent } from "@vue/composition-api";

export default defineComponent({});
</script>
