// blog/index.tsx
import React from "react";
import { LumeDataProps, LumeFilterProps } from "../types.ts";
import { printDate } from "../_utils/datetime.ts";
import { Data } from "lume/core/filesystem.ts";

interface BlogData extends Data {
  title: string;
  url: string;
  date: Date;
  content: string;
  description?: string;
}

export const layout = "layouts/Base.tsx";
export const title = "Wiwa's Blog";

export default ({ search }: LumeDataProps, { md }: LumeFilterProps) => {
  return (
    <div className="max-w-screen-md mx-auto p-4 space-y-5">
      {search.pages("blog", "date=desc").map(({ data }) => {
        const { url, date, title, content, description } = data as BlogData;
        const preview = md(content.split("<!--more-->")[0]);
        return (
          <section>
            <div>
              <span className="font-normal mr-2">{printDate(date)}</span>
              <a href={url} className="bloglist-title">
                <span>{title}</span>
              </a>
            </div>
            {description
              ? <p>{description}</p>
              : <p dangerouslySetInnerHTML={{ __html: preview }} />}
          </section>
        );
      })}
    </div>
  );
};

// pages/blog/index.vue
<template>
  <div class="max-w-screen-md mx-auto p-4 space-y-10">
    <section
      v-for="post in blogPosts"
      :key="post.slug"
      class="flex flex-col space-y-2"
    >
      <div>
        <span class="font-normal mr-2">{{ printDate(post.date) }}</span>
        <nuxt-link :to="post.path" class="bloglist-title"
          ><span>{{ post.title }}</span>
        </nuxt-link>
      </div>
      <p v-if="post.excerpt">{{ post.excerpt }}</p>
    </section>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "@vue/composition-api";
import { printDate } from "@/utils/datetime";

export default defineComponent({
  async asyncData({ $content }) {
    const blogPosts = await $content("blog")
      .only(["title", "slug", "path", "date", "excerpt"])
      .sortBy("date", "desc")
      .fetch();
    return { blogPosts };
  },
  head() {
    return { title: "Wiwa - Blog" };
  },
  setup() {
    return { printDate };
  },
});
</script>
